# Paths
path:
    model_directory: "./model-${exp.model_type}"
    mlflow_dir: "./mlruns" # relative path to the project root

# --------------------------------------------------------------------------------------------------
# exp settings
exp:
    fs: 125
    N_fold: 3
    random_state: 100
    model_type: "toy_model" #"attnunet1d"
    exp_name: "ml-uci-dataset8"
    subject_dict: '/sensorsbp/processed_mimic3/uci_dataset/all_dataset8_df.pkl' # mix_split_df.pkl
    loader: "feature"

# --------------------------------------------------------------------------------------------------
# features & labels

# data laading / features
param_loader:
    phase_match: True
    filtered: True
    feat: [None] #["vpg"] 
    ppg_norm: "loc_z" # glob_mm, glob_z, loc_z, loc_mm
    bp_norm: "glob_mm" # glob_mm, glob_z, loc_z, loc_mm
    label: "sbp"
    
# --------------------------------------------------------------------------------------------------
# trainer param
objective:
  type: "val_mse"
  mode: "min"
param_trainer:
    max_epochs: 1
    check_val_every_n_epoch: 1
    progress_bar_refresh_rate: 5
    gpus: "1"
    auto_lr_find: True
    auto_scale_batch_size: "binsearch"
param_early_stop:
    monitor: ${objective.type}
    min_delta: 0.00
    patience: 5
    verbose: True
    mode: ${objective.mode}


# --------------------------------------------------------------------------------------------------
#  model param
param_model:
    kernel: "rbf"
    C: 10


# --------------------------------------------------------------------------------------------------
logger:
    param_ckpt:
        # dirpath: ${model_directory}
        monitor: ${objective.type}
        filename: "{epoch:02d}-{${objective.type}:.3f}"
        save_top_k: 1
        mode: ${objective.mode}
    log_lightning: False
